spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        # 用户服务
        - id: user-service
          # 负载均衡写法
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        # 评测服务
        - id: judge-service
          uri: lb://judge-service
          predicates:
            - Path=/api/judge/**
        # 题目服务
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/question/**
  application:
    name: gateway
  main:
    web-application-type: reactive
server:
  port: 7069
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
